version: '3.4'

services:
  db:
    image: mysql:9.1.0
    environment:
      TZ: America/Sao_Paulo  #timezone
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: curso_spring_mate # nome do banco de dados
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:  #rede 
      - ana-network
  projeto-person-matematico: # imagem do meu banco
    image: anafelix0909/projeto-person-matematico
    restart: always
    build: .
    working_dir: /matematico
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/curso_spring_mate?userTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    command: mvn spring-boot:run
    ports:
      - 80:80
    depends_on:
      - db
    networks: #rede 
      - ana-network

  portainer:  #O Portainer é uma interface gráfica (GUI) para gerenciar Docker de forma fácil e visual, sem precisar usar só o terminal.
      image: portainer/portainer-ce:latest
      restart: always
      ports: #localhost:9000
        - 9000:9000 #vai subir na pa porta 9000 dentro e fora do container
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      networks: #rede
        - ana-network
volumes:
      portainer_data:

networks: # definição da rede que os containers vão usar
    ana-network:
      driver: bridge
